services:
  kicker-league-scanner:
    image: kicker-league-scanner
    container_name: kicker-league-scanner
    ports:
      - "5000:80"
    restart: unless-stopped
    volumes:
      - /data/kicker-league-scanner/downloaded-matches:/app/downloaded-matches
