services:
  kicker-league-scanner:
    image: kicker-league-scanner
    container_name: kicker-league-scanner
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /data/kicker-league-scanner/downloaded-matches:/app/downloaded-matches
